- name: Install dependencies
  ansible.builtin.apt:
    name: gnupg
    state: present

- name: Add public key
  ansible.builtin.apt_key:
    url: https://download.spotify.com/debian/pubkey_5384CE82BA52C83A.asc
    keyring: /etc/apt/trusted.gpg.d/spotify.gpg
    state: present

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: deb https://repository.spotify.com stable non-free
    filename: spotify.list
    state: present
    update_cache: true

- name: Install latest version
  ansible.builtin.apt:
    name: spotify-client
    state: present
